# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class WebrtcPiping < Formula
  desc "WebRTC tunnel with Piping Server WebRTC signaling"
  homepage "https://github.com/nwtgck/go-webrtc-piping"
  version "0.5.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/nwtgck/go-webrtc-piping/releases/download/v0.5.0/webrtc-piping-0.5.0-darwin-amd64.tar.gz"
      sha256 "e5de6a0e18fc15e216258401537a4df24b941427c1d604aa637001582337d14b"

      def install
        bin.install "webrtc-piping"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/nwtgck/go-webrtc-piping/releases/download/v0.5.0/webrtc-piping-0.5.0-darwin-arm64.tar.gz"
      sha256 "896cea3ee3d76226aa2367be64ce390c53f4677834daf41f4e4b35150c8ec8b1"

      def install
        bin.install "webrtc-piping"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && !Hardware::CPU.is_64_bit?
      url "https://github.com/nwtgck/go-webrtc-piping/releases/download/v0.5.0/webrtc-piping-0.5.0-linux-armv6.tar.gz"
      sha256 "3a7b993f97891d401972cf26b83d5f56c3baf46c548635f6a34cc23da9076697"

      def install
        bin.install "webrtc-piping"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/nwtgck/go-webrtc-piping/releases/download/v0.5.0/webrtc-piping-0.5.0-linux-amd64.tar.gz"
      sha256 "922ec08da54e6fc0dd7f896412f5e780d98599b6bfd2dfe2a1ff342f645f198d"

      def install
        bin.install "webrtc-piping"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/nwtgck/go-webrtc-piping/releases/download/v0.5.0/webrtc-piping-0.5.0-linux-arm64.tar.gz"
      sha256 "12a90bdf9fd25cf7bbe835da4003caad3aad71bb52afbd42961c100ddf451273"

      def install
        bin.install "webrtc-piping"
      end
    end
  end
end
