# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class WebrtcPiping < Formula
  desc "WebRTC tunnel with Piping Server WebRTC signaling"
  homepage "https://github.com/nwtgck/go-webrtc-piping"
  version "0.4.0"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/nwtgck/go-webrtc-piping/releases/download/v0.4.0/webrtc-piping-0.4.0-darwin-arm64.tar.gz"
      sha256 "9ea376d93a1858d75b2659c22d635507877fe865392a4b015989164f230d46df"

      def install
        bin.install "webrtc-piping"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/nwtgck/go-webrtc-piping/releases/download/v0.4.0/webrtc-piping-0.4.0-darwin-amd64.tar.gz"
      sha256 "49a6adb6b428fc0f74f82787de9047cc5e01b5c93c939e8db39fb219c873f4c7"

      def install
        bin.install "webrtc-piping"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && !Hardware::CPU.is_64_bit?
      url "https://github.com/nwtgck/go-webrtc-piping/releases/download/v0.4.0/webrtc-piping-0.4.0-linux-armv6.tar.gz"
      sha256 "7edebaaa7e3aab7470391b7aaecff5788f96449081aa09458137fc93e9966433"

      def install
        bin.install "webrtc-piping"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/nwtgck/go-webrtc-piping/releases/download/v0.4.0/webrtc-piping-0.4.0-linux-amd64.tar.gz"
      sha256 "bdd3d170ee51ee7f596d787aed27d525a28419081b6fa5f54a450b6dc471c2c6"

      def install
        bin.install "webrtc-piping"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/nwtgck/go-webrtc-piping/releases/download/v0.4.0/webrtc-piping-0.4.0-linux-arm64.tar.gz"
      sha256 "e9ef3b34404c817ba01c67a3155b03e309e11d181ab25d61b6011cb27921ba76"

      def install
        bin.install "webrtc-piping"
      end
    end
  end
end
